---
- name: Pull Docker Image
  hosts: ubuntu18
  remote_user: ck
  become: yes
  become_method: sudo
  tasks:
    - name: Pull Frontend from Docker Hub
      docker_image:
        name: docker123chetan/frontendimage:v1
        source: pull
